Sprint 12
agolokoz/ImageFeed-ios pull request #5
Opened 2023-09-02 12:09 UTC by agolokoz

2023-09-02 14:46 UTC, protos17 requested changes

2023-09-02 14:46 UTC, protos17 commented on ImageFeed/Presentation/SingleImageViewController.swift
> +        let scale = clamp(min(hScale, vScale), minZoomScale, maxZoomScale)
Неправильно установлен scale:

let scale = min(maxZoomScale, max(minZoomScale, max(hScale, vScale)))

2023-09-02 14:46 UTC, protos17 commented on ImageFeed/Presentation/SingleImageViewController.swift
>          scrollView.layoutIfNeeded()
Не установлен contentOffset, из-за чего неверно масштабируется:

        let newContentSize = scrollView.contentSize
        let x = (newContentSize.width - visibleRectSize.width) / 2
        let y = (newContentSize.height - visibleRectSize.height) / 2
        scrollView.setContentOffset(CGPoint(x: x, y: y), animated: false)

2023-09-02 14:46 UTC, protos17 commented on ImageFeed/Models/PhotoResult.swift
> +        case createdAt = "created_at"
Если CodingKey совпадает с полем, можно его дополнительно не указывать:

case id
case createdAt = "created_at"

2023-09-02 14:46 UTC, protos17 commented on ImageFeed/Presentation/ImageList/ImageListCell.swift
> +    }()
В ячейке его не стоит хранить. Рекомендую передавать в ячейку в модели не Date, а уже строку, отформатированную в `ImagesListService` и форматтер здесь совсем убрать

2023-09-02 14:46 UTC, protos17 commented on ImageFeed/Presentation/ImageList/ImageListCell.swift
>      private let shadowBottomColor = UIColor(named: "ypBlack")!.withAlphaComponent(CGFloat(0.2))
Не рекомендую использовать принудительное извлечение, даже для цвета

2023-09-02 14:46 UTC, protos17 commented on ImageFeed/Presentation/ImageList/ImageListViewController.swift
> +            guard let cell = cell else { return }
Несколько guard проще писать через запятую:

guard let self = self,
 let cell = cell else { return }

2023-09-02 14:46 UTC, protos17 commented on ImageFeed/Presentation/ImageList/ImageListViewController.swift
> +                UiBlockingProgressHUD.dismiss()
Чтобы не дублировать, лучше вынести в общую область видимости, а в failure обработать и показать ошибку пользователю

2023-09-02 14:46 UTC, protos17 commented on ImageFeed/Presentation/ShimmerAnimation.swift
> +class ShimmerAnimation {
Класс без наследования рекомендую указать как final

2023-09-02 14:46 UTC, protos17 commented on ImageFeed/Services/ImagesListService.swift
> +            print("Token is empty")
Рекомендую принты использовать только для отладки, в репозиторий их пушить не принято

2023-09-03 09:44 UTC, agolokoz commented on ImageFeed/Presentation/SingleImageViewController.swift
> +        let scale = clamp(min(hScale, vScale), minZoomScale, maxZoomScale)
С таким подходом при открытии горизонтальных картинок будет показана только левая верхняя часть, и чтобы увидеть картинку целиком, нужно будет отскейливать обратно

2023-09-03 09:53 UTC, agolokoz commented on ImageFeed/Services/ImagesListService.swift
> +            print("Token is empty")
Так он только для отладки и есть. Если что-то пойдёт не так и я увижу в логах этот текст, я сразу буду понимать в чём дело, иначе нужно будет включать дебаггер и проходиться по шагам, что займёт больше времени

2023-09-03 09:54 UTC, protos17 commented on ImageFeed/Services/ImagesListService.swift
> +            print("Token is empty")
Ну в финальную версию их не нужно сохранять

2023-09-03 10:29 UTC, agolokoz commented on ImageFeed/Services/ImagesListService.swift
> +            print("Token is empty")
А если потом что-то пойдёт не так, заново расставлять?

2023-09-03 10:31 UTC, protos17 commented on ImageFeed/Services/ImagesListService.swift
> +            print("Token is empty")
Дебаг - процесс поиска и отладки ошибки, если приложение работает корректно, то принты абсолютно не нужны. При поиске багов нужно будет расставить их в нужном порядке, найти и исправить баг и удалить. Если в большом приложении все эти принты расставить, то в консоли будет полный хаос и нужную информацию для дебага ты там точно не найдешь

2023-09-03 10:35 UTC, agolokoz commented on ImageFeed/Services/ImagesListService.swift
> +            print("Token is empty")
Разработка – процесс долгий и чаще всего происходит он в команде, где может работать много человек. Когда много человек (да даже если и один) задевает один код, свойственно появляться ошибкам, которые проще отловить, когда в логах выводится информация. 
На этом учебном проекте я разработчик, я не хочу тратить кучу времени на поиск ошибок, убрав вывод информации в лог, потому что так "не принятно". И ещё не понятно кем не принято.

2023-09-03 10:39 UTC, protos17 commented on ImageFeed/Services/ImagesListService.swift
> +            print("Token is empty")
Так принято на всех работах, на которых я работал. Во всяком случае, это лишь мои рекомендации и на принятие спринта они не влияют

2023-09-03 12:18 UTC, protos17 approved these changes

2023-09-03 12:18 UTC, protos17 commented on ImageFeed/Presentation/ImageList/ImageListViewController.swift
>          NSLayoutConstraint.activate([
Чтобы таблица имело правильно поведение при пролистывании, здесь нужно заменить констрейнт:

tableView.topAnchor.constraint(equalTo: view.topAnchor)

2023-09-03 12:18 UTC, protos17 commented on ImageFeed/Presentation/ShimmerAnimation.swift
> +import Foundation
При импорте UIKit можно не импортировать Foundation, потому что первый содержит в себе второй

2023-09-03 12:18 UTC, protos17 commented on ImageFeed/Presentation/SplashViewController.swift
>                  profileImageService.fetchProfileImageUrl(username: profile.username) { _ in }
showTabBarController() лучше перенести в это замыкание, таким образом будет соблюден порядок получения данных и отображения приложения

2023-09-03 12:18 UTC, protos17 commented on ImageFeed/Services/ImagesListService.swift
> +            print("Token is empty")
При отладке, особенно в таких местах, как else в guard, лучше вместо print использовать assertionFailure, тогда код остановится в этом месте и будет явно видно, где ошибка.
Подробнее про ассерты: https://www.hackingwithswift.com/plus/intermediate-swift/understanding-assertions

2023-09-03 12:18 UTC, protos17 commented on ImageFeed/Services/ImagesListService.swift
> +                    let newPhotos = photoResults.map { self.mapPhotoResultToPhoto($0) }
Здесь неявная сильная ссылка. При map мы также имеем дело с замыканием, поэтому здесь тоже стоит указать weak self

2023-09-03 12:18 UTC, protos17 commented on ImageFeed/Services/ImagesListService.swift
> +            print("Token is empty")
Здесь тогда тоже лучше указать assertionFailure
https://stevenpcurtis.medium.com/precondition-assert-fatal-error-or-guard-in-your-swift-code-5f9297658be0

2023-09-03 12:18 UTC, protos17 commented on ImageFeed/Services/OAuth2TokenStorage.swift
>      private static let KeyBearerToken = "bearer"
Константы принято писать с маленькой буквы

2023-09-28 13:46 UTC, merged